version: '3.5'

services:
  app:
    container_name: project
    build: ./
    ports:
      - '3001:3001'
    tty: true
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - monogVolume:/data/db
volumes:
  monogVolume:
